In [19]:
import pandas as pd

dataset = pd.read_csv('data/train.csv')

In [4]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=2, shuffle=True, random_state=42)
for train_index, val_index in kf.split(dataset):
    print(train_index)

[    1     2     4 ... 15109 15111 15117]
[    0     3     8 ... 15116 15118 15119]


In [17]:
df = dataset.to_numpy()[train_index]
df[:-2]

array([[    1,  2596,    51, ...,     0,     0,     5],
       [    4,  2785,   155, ...,     0,     0,     2],
       [    9,  2617,    45, ...,     0,     0,     5],
       ...,
       [15115,  2670,   108, ...,     0,     0,     3],
       [15116,  2607,   243, ...,     0,     0,     3],
       [15117,  2603,   121, ...,     0,     0,     3]], dtype=int64)

In [24]:
from sklearn.model_selection import train_test_split

dataset.columns = dataset.columns.str.lower()

features = dataset.drop('cover_type', axis=1)
target = dataset['cover_type']
features_train, features_val, target_train, target_val = train_test_split(
    features, target, test_size=0.3, random_state=42
) 

kf = KFold(n_splits=2, shuffle=True, random_state=42)
for train_index, val_index in kf.split(features, target):
    print(train_index, val_index)

[    1     2     4 ... 15109 15111 15117] [    0     3     8 ... 15116 15118 15119]
[    0     3     8 ... 15116 15118 15119] [    1     2     4 ... 15109 15111 15117]


In [34]:
features_train.shape

(5292, 55)

In [40]:
features = dataset.drop('cover_type', axis=1).to_numpy()
target = dataset['cover_type'].to_numpy()
features_train, features_val, target_train, target_val = train_test_split(
    features, target, test_size=0.3, random_state=42
)    

kf = KFold(n_splits=2, shuffle=True, random_state=42)
for train_index, target_index in kf.split(features_train, target_train):
    X, y = features_train[train_index], target_train[target_index]

In [43]:
X

array([[  766,  2916,   228, ...,     0,     0,     0],
       [ 6188,  2415,   270, ...,     0,     0,     0],
       [ 9480,  3247,   186, ...,     0,     0,     0],
       ...,
       [11965,  2102,   100, ...,     0,     0,     0],
       [  861,  2898,   254, ...,     0,     0,     0],
       [ 7271,  3374,    78, ...,     1,     0,     0]], dtype=int64)

In [45]:
y.T

array([3, 2, 3, ..., 4, 4, 2], dtype=int64)

In [49]:
dataset[dataset.id == 6188]

id  elevation  aspect  slope  horizontal_distance_to_hydrology  \
6187  6188       2415     270     29                               108   

      vertical_distance_to_hydrology  horizontal_distance_to_roadways  \
6187                              43                             1429   

      hillshade_9am  hillshade_noon  hillshade_3pm  ...  soil_type32  \
6187            131             235            235  ...            0   

      soil_type33  soil_type34  soil_type35  soil_type36  soil_type37  \
6187            0            0            0            0            0   

      soil_type38  soil_type39  soil_type40  cover_type  
6187            0            0            0           6  

[1 rows x 56 columns]

In [50]:
np.arange(0, 200, 20)

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost

esatimator_pipline = {
    'LogReg': LogisticRegression(),
    'RFC': RandomForestClassifier(),
    'XGB': xgboost(),
}